services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    image: grafana/grafana:8.4.5
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"

  app:
    build: ./app
    container_name: jr_go_app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    container_name: tns-db
    ports:
      - 8082:80
    networks:
      - grafana

networks:
  grafana:

volumes:
  app_data: {}